Refactor runASTAnalysis functions to use class AstAnalyser
NodeSecure/js-x-ray pull request #216
Opened 2024-01-27 18:36 UTC by jean-michelet

The aim of this PR is to make the project more flexible and allow users to add new behaviors more easily.

I've created an `AstAnalyser` class that implements the logic originally contained in `runASTAnalysis` and `runASTAnalysisOnFile`. The class can be extended and has a dependency on any EStree-compatible parser that respects the following abstraction:
```ts
interface SourceParser {
  parse(source: string, options: unknown): ESTree.Program;
}

interface AstAnalyser {
  constructor(parser: SourceParser): void;
  analyse: (str: string, options?: Omit<RuntimeOptions, "customParser">) => Report;
  analyzeFile(pathToFile: string, options?: Omit<RuntimeFileOptions, "customParser">): Promise<ReportOnFile>;
}
```
Example:
```js
const jsAnalyser = new AstAnalyser(new JsSourceParser());
const tsAnalyser = new AstAnalyser(new TsSourceParser());
```
I removed the  class `SourceParser` and favor ***composition over inheritance***. 
Responsibility for preparing source code (deleting html comments etc.) for analysis can be assigned to the new class `AstAnalyser`. It remove the need for this class from the workspaces, wich could be problematic to create the `TsSourceParser` ([214](https://github.com/NodeSecure/js-x-ray/issues/214)).

I kept the functions `runASTAnalysis` and `runASTAnalysisOnFile` so my additions extend the possibilities without breaking the existing. Users can pass a custom parser to these functions without having to completely modify their code:
```js
function runASTAnalysis(
  str,
  options = Object.create(null)
) {
  const {
    customParser = new JsSourceParser(),
    ...opts
  } = options;

  const analyser = new AstAnalyser(customParser);

  return analyser.analyse(str, opts);
}
```

I've deported the tests for these functions to the new `AstAnalyser` class and replaced them with integration tests verifying that the functions call the `AstAnalyser` methods with the right arguments.

2024-01-27 20:45 UTC, fraxken requested changes

2024-01-27 20:45 UTC, fraxken commented on types/api.d.ts
> +interface AstAnalyser {
declare class AstAnalyser plutôt non?

2024-01-27 20:45 UTC, fraxken commented on types/api.d.ts
> +interface SourceParser {
declare class

2024-01-27 20:45 UTC, fraxken commented on src/AstAnalyser.js
> +import path from "path";
You need to add `node:` prefix

2024-01-27 20:45 UTC, fraxken commented on src/AstAnalyser.js
> +   * @param { Parser } parser
What is Parser type?

2024-01-27 21:28 UTC, jean-michelet commented on src/AstAnalyser.js
> +import path from "node:path";
Ooops @fraxken 

Added this fix in the wrong commit bu it's there

2024-01-28 17:11 UTC, fraxken approved these changes

2024-01-28 18:02 UTC, PierreDemailly approved these changes

2024-01-28 20:50 UTC, merged

2024-01-28 20:52 UTC, fraxken commented
@allcontributors please add @jean-michelet for code, test, doc