Use JsSourceParser as default parser for AstAnalyser class
NodeSecure/js-x-ray pull request #227
Opened 2024-01-31 16:31 UTC by madina0801

It was suspiciously easy, let me know if there are any issues :)

2024-01-31 16:51 UTC, PierreDemailly commented
Thanks for contributing, could you update the type here? https://github.com/NodeSecure/js-x-ray/blob/7422acba002fc75059a016c6e10a29ec575a6437/types/api.d.ts#L81

2024-01-31 17:08 UTC, fraxken commented
You can probably write a new test in https://github.com/NodeSecure/js-x-ray/blob/master/test/AstAnalyser.spec.js

If we declare the class without any parser and then use it (it should not throw any error).

2024-02-01 09:13 UTC, PierreDemailly requested changes

2024-02-01 09:13 UTC, PierreDemailly commented on test/AstAnalyser.spec.js
> +        const analyser = getAnalyser();
Actually this test is wrong.
The `getAmalyser()` function returns the `AstAnalyser` instanciated with `JsSourceParser()`.

```js
analyser = new AstAnalyser(new JsSourceParser());
```

```suggestion
        const analyser = new AstAnalyser();
```

2024-02-02 06:57 UTC, PierreDemailly approved these changes

2024-02-02 17:49 UTC, fraxken approved these changes

2024-02-02 17:49 UTC, merged

2024-02-02 17:50 UTC, fraxken commented
@allcontributors please add @madina0801 for code