feat: detect weak crypto algorithm
NodeSecure/js-x-ray pull request #30
Opened 2022-05-24 18:27 UTC by tony-go

## Context

This PR resolves issue #25 

## Improvements 🚀 

At the moment we detect:

| Algorithm | Code              | import 'crypto' |
|-----------|-------------------|-----------------|
| `md5`     | createHash('md5') |  ✅              |
| `md5`     | crypto.createHash('md5') |  ✅              |

## Questions

- Should we make `import 'crypto'` be required to trigger this warning?
- Should I add other weak crypto algorithms in this PR? (like `sha1`, but TBH I don't know other ones 🙈)?

2022-05-27 12:14 UTC, Kawacrepe reviewed
Lgtm! My only question is: shouldn't we add a valid test case ? where the cryptoHash algorithm used is something like sha256 etc..?

2022-05-27 18:08 UTC, tony-go commented
> Lgtm! My only question is: shouldn't we add a valid test case ? where the cryptoHash algorithm used is something like sha256 etc..?

Very good idea ^^ I'll add it.

2022-05-28 06:46 UTC, Kawacrepe approved these changes

2022-05-30 15:13 UTC, tony-go commented
@fraxken do you prefer to wait for the tracer feature?

2022-05-30 16:39 UTC, fraxken commented
@tony-go No i guess this is ok to merge. For weak hash i have found this list
- MD2, MD4, MD5, RIPEMD-160, and SHA-1

SHA1 is supported by Node.js (maybe we have to check for the other ones).

2022-05-30 16:42 UTC, fraxken requested changes

2022-05-30 16:42 UTC, fraxken commented on src/probes/isWeakCrypto.js
> +  }
Make the code dynamic to check multiple hash algorithms. The list of vulnerable hashes could be stored in an ES6 Set.

2022-05-30 16:42 UTC, fraxken commented on index.js
> +    severity: "Information"
Maybe we should add another property `experimental: true` here ? So other tools like CLI may use this to show an experimental note.

2022-06-02 09:40 UTC, fraxken commented on src/probes/isWeakCrypto.js
> +const weakAlgorithms = ["md5", "sha1", "ripemd160", "md4", "md2"];
`new Set(["md5", "sha1", "ripemd160", "md4", "md2"])` no ?

2022-06-02 09:40 UTC, fraxken commented on src/probes/isWeakCrypto.js
> +    weakAlgorithms.includes(arg.value) &&
```js
weakAlgorithms.has(arg.value)
```

With an ES6 Set

2022-06-02 10:04 UTC, tony-go commented on src/probes/isWeakCrypto.js
> +const weakAlgorithms = ["md5", "sha1", "ripemd160", "md4", "md2"];
Shame on me! this is the vim effect!

2022-06-02 10:10 UTC, tony-go commented on src/probes/isWeakCrypto.js
> +    weakAlgorithms.includes(arg.value) &&
🙈

2022-06-02 10:24 UTC, merged

2022-06-02 10:25 UTC, fraxken commented
@all-contributors please add @tony-go for code,tests,docs

2022-06-02 10:33 UTC, fraxken commented
@all-contributors please add @tony for code, doc, test